{
	parserClass="cappuccino.ide.intellij.plugin.parser.ObjJCommentParser"
	implements="cappuccino.ide.intellij.plugin.comments.ObjJCommentElement"
	extends="cappuccino.ide.intellij.plugin.comments.ObjJCompositeElementImpl"
	elementTypeHolderClass="cappuccino.ide.intellij.plugin.comments.ObjJCommentTypes"
	elementTypePrefix="ObjJComment_"
	elementTypeClass="cappuccino.ide.intellij.plugin.comments.ObjJCommentElementType"
	tokenTypeClass="cappuccino.ide.intellij.plugin.comments.ObjJCommentToken"
	psiClassPrefix="ObjJComment"
	psiImplClassSuffix="Impl"
	psiPackage="cappuccino.ide.intellij.plugin.comments.psi"
	psiImplPackage="cappuccino.ide.intellij.plugin.comments.psi.impl"
	//Tokens
	tokens = [
		//Line Terminator
		LINE_TERMINATOR =                 	'regexp:[\r\n\u2028\u2029]';
		START =								"regexp:/[*]+"
		END =								'regexp:[*]+/'
		LEADING_ASTERISK =					'regexp:[*]+'
		TEXT =								'___TEXT___'
		CODE_BLOCK_TEXT =					'___CODE_BLOCK_TEXT___'
		TAG_NAME =							'___TAG_NAME___'
		PIPE = 								"|";
		COMMA =								',';
		PIPE = 								'|';
		QUALIFIED_NAME =					'___QUALIFIED_NAME___'
		TEXT =								'regexp:[^ \n$]+';
		ID = 								'regexp:[_a-zA-Z$][a-zA-Z0-9_]*';
	]
}

comment ::= (!<<eof>> LINE_PREFIX* commentLine)*;

private commentLine
	::= paramLine
	|	returnLine
	|	ignoreLine
	|	varLine
	|	textLine
	|	LINE_TERMINATOR
	;

paramLine
	::= AT_PARAM  classNameList variableName textLine? endOfLine
	{
		pin=1;
	}
	;

returnLine
	::= AT_RETURN classNameList? textLine? endOfLine
	{
		pin=1;
	}
	;

ignoreLine
	::= AT_IGNORE ignoreFlag ((','|'|') ignoreFlag)* endOfLine
	{
		pin = 1
	}
	;

varLine
	::= AT_VAR classNameList variableName? textLine? endOfLine
	{
		pin=1
	}
	;

textLine
	::= (text|ID|AT_ALT)+
	;


private classNameList
	::= className('|'className)*
	;


className ::= ID;

ignoreFlag ::= ID;

variableName
	::= ID
	;

endOfLine
	::= LINE_TERMINATOR | <<eof>>
	;
