package cappuccino.ide.intellij.plugin.references

val ObjJGlobalJsVariableNames = listOf(
        // Math
        "E", "LN2", "LN10", "LOG", "LOG2E", "LOG10E", "PI", "PI2", "PI_2", "SQRT1_2", "SQRT2",
        // CFErrors.js
        "kCFErrorLocalizedDescriptionKey",
        "kCFErrorLocalizedFailureReasonKey",
        "kCFErrorLocalizedRecoverySuggestionKey",
        "kCFErrorDescriptionKey",
        "kCFErrorUnderlyingErrorKey",
        "kCFErrorURLKey",
        "kCFErrorFilePathKey",
        "kCFErrorDomainCappuccino",
        "kCFErrorDomainCocoa",
        // CFNetworkErrors.js
        "kCFURLErrorUnknown",
        "kCFURLErrorCancelled",
        "kCFURLErrorBadURL",
        "kCFURLErrorTimedOut",
        "kCFURLErrorUnsupportedURL",
        "kCFURLErrorCannotFindHost",
        "kCFURLErrorCannotConnectToHost",
        "kCFURLErrorNetworkConnectionLost",
        "kCFURLErrorDNSLookupFailed",
        "kCFURLErrorHTTPTooManyRedirects",
        "kCFURLErrorResourceUnavailable",
        "kCFURLErrorNotConnectedToInternet",
        "kCFURLErrorRedirectToNonExistentLocation",
        "kCFURLErrorBadServerResponse",
        "kCFURLErrorUserCancelledAuthentication",
        "kCFURLErrorUserAuthenticationRequired",
        "kCFURLErrorZeroByteResource",
        "kCFURLErrorCannotDecodeRawData",
        "kCFURLErrorCannotDecodeContentData",
        "kCFURLErrorCannotParseResponse",
        "kCFURLErrorRequestBodyStreamExhausted",
        "kCFURLErrorFileDoesNotExist",
        "kCFURLErrorFileIsDirectory",
        "kCFURLErrorNoPermissionsToReadFile",
        "kCFURLErrorDataLengthExceedsMaximum",
        "kCFPropertyListOpenStepFormat",
        "kCFPropertyListXMLFormat_v1_0",
        "kCFPropertyListBinaryFormat_v1_0",
        "kCFPropertyList280NorthFormat_v1_0",
        "CPLogDisable"
)