package org.cappuccino_project.ide.intellij.plugin.stubs.interfaces

import org.cappuccino_project.ide.intellij.plugin.psi.impl.ObjJFunctionDeclarationImpl

interface ObjJFunctionDeclarationStub : ObjJFunctionDeclarationElementStub<ObjJFunctionDeclarationImpl>
